trailblazer/reform

README.md

While diving into reform I noticed that there is no info about input type guess for simple_form, but afterwards I found a note about that [in changelog][1].
This PR adds the note to README to avoid confusion.
[1]: https://github.com/apotonick/reform/blob/master/CHANGES.md#breakage

Include a note about ModelReflections in README

---

README.md
lib/reform/contract.rb

When I tried to use virtual attributes as mentioned in original readme I was confused because it didn't work.  
This is a fix for readme and deprecation warning message to avoid confusion.
Also, I updated wiki page https://github.com/apotonick/reform/wiki/Migration-Guide

We haven't had 2.0 virtual attributes by default yet

---

.travis.yml

I believe `2.1.5` and `2.2.0` is more up to date at the moment. Also, it's always better to know sooner if something is failing on ruby master.

Run tests against new ruby versions on travis

---

test/model_reflections_test.rb
test/validate_test.rb

(1) First test had extra 's'.
(2) Second test incorrectly tested instance_of rather than kind_of when testing the reflection.  (See the [class hierarchy in active_record/reflection.rb](https://github.com/rails/docrails/blob/master/activerecord/lib/active_record/reflection.rb#L165-L174).)

Correct Failing Tests

---

lib/reform/mongoid.rb

Fix mongoid dependency on model_reflection because the file was moved on commit d37829019ced4f7d0ba1e4f896d576689c9474ca

Fix mongoid dependency on active_model/model_reflections.

---

lib/reform/form/active_model/validations.rb
lib/reform/form/lotus.rb

Per conversion in #263 
`valid?` is widely used method in Rails and Lotus apps whereas in Reform
this method is undocumented, is not a part of public interface, and
should be used only in Reform internals.
Making `valid?` private should raise awareness to developers that they
might be calling something they shouldn't.

Make `valid?` private

---

lib/reform/form/active_record.rb
test/active_record_test.rb

fix issue for #249
BTW,  currently(the master branch) the hash for block params is: 
1. symbol access key for model of  composition form
2. string access key for attribute
would you mind to change it all to string key or symbl key, when no acitve_record, no AS:HWIA

cast block hash to HWIA for active_record form

---

lib/reform/form/multi_parameter_attributes.rb
test/multi_parameter_attributes_test.rb

This solve https://github.com/apotonick/reform/pull/267 without catch generic exceptions or any other. I use the same test at the other PR.

Fix invalid date issue without catch or raise exception

---

lib/reform/form/validation/unique_validator.rb
test/dummy/config/locales/en.yml
test/unique_test.rb

Add :taken symbol as error to form if uniqueness validation fails. This
mimics the uniqueness validation from active model, making translation
of the error message possible, inheriting the default translations from
active_model / rails.

Use I18n for error message in uniqueness validator

---

lib/reform/form/validation/unique_validator.rb
test/unique_test.rb

Simple scope option! Yey!
To use it:
`validates :title, unique: { scope: :album_id }`
It checks only song with the same title by album instead of all the songs available.

Add scope options to unique validation

---

CHANGES.md
lib/reform/form/active_model/validations.rb

The  `ActiveModel::Validations::AcceptanceValidator` and `ActiveModel::Validations::ConfirmationValidator` attempt to define `attr_reader` and `attr_writer` methods on the model, which conflicts with the delegate approach for implementing `Validator`.
#262 suggests to use our own `AcceptValidator`
This is another solution to make acceptance and confirmation validations work by preventing Rails from adding methods to the `Validator`. The accessors will now properly delegate to the form object.
A common pattern I saw in the gitter chat is people taking the validations out of their AR models and moving them to a `Reform::Form` (either with Trailblazer or without), so making sure that the default Rails validations work will really smooth the transition to TRB/Reform.
@apotonick I know you are …

Prevent Rails from adding methods to validator

---

README.md

This Readme update is driven by the following issue: https://github.com/apotonick/reform/issues/230
It is unreasonable to expect people to keep the copy_validations_from line under the property definitions. We should explicitly let people know this structure is required.

Updated Readme for copy_validations_from

---

test/skip_if_test.rb

Found this while doing other work. This fails with the message:
```
NoMethodError: undefined method `validate!' for nil:NilClass
/Users/shep/Projects/reform/lib/reform/contract/validate.rb:28:in `block (2 levels) in validate_nested!'
/Users/shep/.rvm/gems/ruby-2.2.1/gems/disposable-0.2.0.rc1/lib/disposable/twin/property_processor.rb:24:in `block in collection!'
/Users/shep/.rvm/gems/ruby-2.2.1/gems/disposable-0.2.0.rc1/lib/disposable/twin/property_processor.rb:24:in `collect'
/Users/shep/.rvm/gems/ruby-2.2.1/gems/disposable-0.2.0.rc1/lib/disposable/twin/property_processor.rb:24:in `collection!'
/Users/shep/.rvm/gems/ruby-2.2.1/gems/disposable-0.2.0.rc1/lib/disposable/twin/property_processor.rb:15:in `call'
/Users/shep/Projects/reform/lib/reform/contract/validate.rb:28:in `block in …
```

[Do Not Merge] Reproduction that skip_if doesn't work if the first item is skipped

---

README.md

The [official documentation](http://trailblazer.to/gems/reform/#installation) states that when installing, you should require `reform/form/dry` when setting up `dry-validation`, not `reform/form/lotus` (as in the readme).
In Rails 4.2 and by only installing the reform gem (latest version as of this time of writing), using the instructions in the readme will result in a `LoadError`.
This should make things less confusing for people using the repo's documentation.
Hope this helps!

Fix require statement in readme

---

lib/reform/contract.rb
test/contract_test.rb

Previous to this commit, calling `properties` without providing
an options Hash would result in an attempt to dup `nil`.
This fixes the issues and adds basic specs for `Contract.properties`.
Relates to #371.

Fixing Contract.properties to handle empty options

---

lib/reform/form.rb
test/parse_option_test.rb

Allow defining *parse* properties that cannot be updated at `Form#validate`:
```ruby
User = Struct.new(:name, :admin)
class UserForm < Reform::Form
property :name
property :admin, parse: false
end
user = User.new("Peter", false)
form = UserForm.new(user)
form.validate("name" => "Joseph", "admin" => true)
form.name # returns "Joseph"
form.admin # returns false
```

Add :parse option for property

---

lib/reform/validation.rb

(same as validation group) from hash or positional args.  This is needed to be compatible with @fran-worley's #385, but with the deprecation change from @apotonick's 04c4063a0a87073811ca2170147540570b31dfcf.  The latest commit after fran's merge allowed a hash to be passed as a name to heritage.

ensure heritage uses the resolved name 

---

test/inherit_test.rb
test/test_helper.rb

The `subject.validate` tests can be restored with some fairly minor syntax changes to be compatible with dry-validation.
There may be reasons to keep some of these tests commented-out that I'm not aware of.
The motivation for this clean-up is that I'm encountering some odd behaviour (possibly a bug, possibly a misunderstanding on my part) around inherited populators, and having a more thorough set of tests here is a prerequisite for me writing some tests to verify whether my issue is a bug or not.
cheers

Clean up and restore some inherit_test code.

---

lib/reform/contract/errors.rb
test/errors_test.rb

This improves compatibility with ActiveModel-style errors (which seems to be a goal of the gem, according to the docs and #345), and also makes integration with some gems other gems easier.
For example, some of the views for the devise authentication gem expect that an `errors` object will respond to `count`.
Obviously AM compatibility could be pushed further, but these changes are fairly innocuous and straightforwardly helpful.

Add `Errors#count` and `#size` methods.

---

lib/reform/form.rb

Unless you've manually opted into it, the call to `super` here will go through the disposable and declarative gems, but not representable.
This is obviously a very minor change, but caused a bit of confusion for me when attempting to understand the source code. 
Of course, my understanding may be wrong, feel free to close the PR if it is.

Update stale comment about use of representable gem.

---

.travis.yml
Rakefile
lib/reform/form.rb
test/skip_if_test.rb

Let's notify the User that using `skip_if` and `populator` is kinda wrong and could create some issues.
This should "fix" https://github.com/trailblazer/reform/issues/434

Raise error when skip_if and populator are used together 

---

CHANGES.md
lib/reform/contract.rb
lib/reform/contract/custom_error.rb
lib/reform/errors.rb
lib/reform/result.rb
test/contract/custom_error_test.rb
test/errors_test.rb

The idea is to add in the `@results` instance variable an object which simulates a Dry schema object so any other part of the code should just work as before.
I have also added the possibility to add an error before actually running a validation (not sure if that makes sense but I don't see why it wouldn't).

Allow to add an error after validation

---

CHANGES.md
lib/reform/validation.rb
test/validate_test.rb

Calls `validate({})`.
The aim of this method is to check if that specific Form instance is valid if model changes a new form instance MUST be created.
We have issues around about calling multiple times validate to the same instance and we know that has problems - this will be fixed in the 3.x

Reintroduce valid?

---

lib/reform/contract/custom_error.rb
lib/reform/contract/validate.rb
lib/reform/result.rb
test/errors_test.rb
test/validation/result_test.rb

In this is possible to have:
```
form.errors.add(:email, "already taken)
form.validate(email: "myemail@email.com")
form.errors.messages(email: ["already taken", "error from validation"])
```
or (maybe more possible):
```
form.validate(email: "my@email.com")
form.errors.add(:email, "something")
unless form.valid?
flash[:error] = form.errors.messages
end
```
**An `add` error will never be clened up by `validate`.... validate a new form instance to have a fresh start**

Allow to add errors before validate

---

lib/reform/form/validate.rb
test/skip_if_test.rb

Ensure AllBlank returns correctly if forms have content, regardless of
type of key used.
Fixes https://github.com/apotonick/reform/issues/367#issuecomment-238605908
The explicit type conversion could be removed if the keys being passed in are guaranteed to be strings, but I'm not familiar enough with Dry schemas to attempt that currently.

Handle strings or symbols as key for AllBlank

---

lib/reform/form/dry.rb
test/module_test.rb

The issue was detected in ~~two~~ one places on each validation call:
1.    initialization of dry-validation contract
2.   ~~initialization new array with constants inside~~
to reproduce:
1) install gem https://github.com/SamSaffron/memory_profiler
2) go to the repository and profile memory consumption by ruby script "mem_leak.rb".
```bash
ruby-memory-profiler --pretty -m 5 mem_leak.rb
```
```ruby
require_relative "lib/reform"
require_relative "lib/reform/form/dry"
class TestForm < Reform::Form
feature Reform::Form::Dry
end
Song = Struct.new(:title)
class Contr < TestForm
validation do
option :form
params do
required(:title).filled(min_size?: 2)
end
rule do
if form == "hello"
base.failure('creating events is allowed only on weekdays')
end
end
end
end
form = Contr.new(Song.new(nil)) …
```

[~] fix memory leak when use "dry-validation"

---

lib/reform/form/dry.rb
lib/reform/form/populator.rb
lib/reform/form/prepopulate.rb
lib/reform/form/validate.rb
reform.gemspec
test/populate_test.rb
test/prepopulator_test.rb

- Use `Representable::Option` instead of `Declarative::Option` to forward `keyword_arguments` as per ruby-3 standards.
- Display a warning while accepting `form` as an explicit positional argument in populator of type `Uber::Callable`. This will be deprecated in future release in order to make it identical with other type of populators (proc, method etc).

Upgrade `representable` and `disposable` to support ruby-3

---

reform.gemspec
test/test_helper.rb

This allows us to use representable 3.2.0 and other new minor versions.

Loosen Representable dependency to allow versions < 4
